"""empty message

Revision ID: 5b3445cc235d
Revises: 7fb51c4005cb
Create Date: 2021-05-09 16:09:14.002677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3445cc235d'
down_revision = '7fb51c4005cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint('questions_category_fkey', 'questions', type_='foreignkey')
    op.execute("""
            UPDATE questions SET category_id = category;
            ALTER TABLE questions ALTER COLUMN category_id SET NOT NULL
    """)
    op.create_foreign_key(None, 'questions', 'categories', ['category_id'], ['id'])
    op.drop_column('questions', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_category_fkey', 'questions', 'categories', ['category'], ['id'])
    op.drop_column('questions', 'category_id')
    # ### end Alembic commands ###
